"""initial schema

Revision ID: 84b43b7954ba
Revises:
Create Date: 2026-09-08 17:21:23.393239

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "84b43b7954ba"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "users",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("username", sa.Text(), nullable=False),
        sa.Column("password_hash", sa.Text(), nullable=False),
        sa.Column("created_at", sa.Text(), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_users")),
        sa.UniqueConstraint("username", name=op.f("uq_users_username")),
    )
    op.create_table(
        "boxes",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("public_id", sa.Text(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("number", sa.Integer(), nullable=False),
        sa.Column("name", sa.Text(), nullable=True),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("location", sa.Text(), nullable=True),
        sa.Column("created_at", sa.Text(), nullable=False),
        sa.CheckConstraint("number >= 1", name=op.f("ck_boxes_number_positive")),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name=op.f("fk_boxes_user_id_users")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_boxes")),
        sa.UniqueConstraint("public_id", name=op.f("uq_boxes_public_id")),
        sa.UniqueConstraint("user_id", "number", name=op.f("uq_boxes_user_id_number")),
    )
    op.create_table(
        "items",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("public_id", sa.Text(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("box_id", sa.Integer(), nullable=False),
        sa.Column("title", sa.Text(), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("image_key", sa.Text(), nullable=True),
        sa.Column("image_original_type", sa.Text(), nullable=True),
        sa.Column("created_at", sa.Text(), nullable=False),
        sa.Column("updated_at", sa.Text(), nullable=False),
        sa.CheckConstraint(
            "length(trim(title)) > 0", name=op.f("ck_items_title_not_blank")
        ),
        sa.ForeignKeyConstraint(
            ["box_id"],
            ["boxes.id"],
            name=op.f("fk_items_box_id_boxes"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name=op.f("fk_items_user_id_users")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_items")),
        sa.UniqueConstraint("public_id", name=op.f("uq_items_public_id")),
    )
    with op.batch_alter_table("items", schema=None) as batch_op:
        batch_op.create_index("ix_items_box_id", ["box_id"], unique=False)
        batch_op.create_index("ix_items_user_id", ["user_id"], unique=False)

    op.create_table(
        "item_tags",
        sa.Column("item_id", sa.Integer(), nullable=False),
        sa.Column("tag", sa.Text(), nullable=False),
        sa.ForeignKeyConstraint(
            ["item_id"], ["items.id"], name=op.f("fk_item_tags_item_id_items")
        ),
        sa.PrimaryKeyConstraint("item_id", "tag", name=op.f("pk_item_tags")),
    )
    with op.batch_alter_table("item_tags", schema=None) as batch_op:
        batch_op.create_index("ix_item_tags_tag", ["tag"], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("item_tags", schema=None) as batch_op:
        batch_op.drop_index("ix_item_tags_tag")

    op.drop_table("item_tags")
    with op.batch_alter_table("items", schema=None) as batch_op:
        batch_op.drop_index("ix_items_user_id")
        batch_op.drop_index("ix_items_box_id")

    op.drop_table("items")
    op.drop_table("boxes")
    op.drop_table("users")
    # ### end Alembic commands ###
